project:
  type: website

website:
  title: "IS415-GAA"
  navbar:
    left:
      - text: "Hands-on Exercise"
        menu:
          - text: "Hands-on Exercise 1"
            href: "Hands-on_Ex01/hands_on_1.html"
          - text: "Hands-on Exercise 2"
            href: "Hands-on_Ex02/hands_on_2.html"
          - text: "Hands-on Exercise 3.1"
            href: "Hands-on_Ex03/hands_on_3_1.qmd"
          - text: "Hands-on Exercise 3.2"
            href: "Hands-on_Ex03/hands_on_3_2.qmd"
          - text: "Hands-on Exercise 4"
            href: "Hands-on_Ex04/Hands-on_Ex04.qmd"
      - text: "In-class Exercise"
        menu:
        - text: "In-class Exercise 2"
          href: "In-class_Ex/In-class_Ex02/In-class_Ex02.html"
        - text: "In-class Exercise 3"
          href: "In-class_Ex/In-class_Ex03/In-class_Ex03.html"
        - text: "In-class Exercise 3 - Network"
          href: "In-class_Ex/In-class_Ex03/In-class_Ex03-Network.html"
        - text: "In-class Exercise 4"
          url: "https://is415-gaa-yozafard.netlify.app/in-class_ex/in-class_ex04/in-class_ex04" 
      - text: "Take Home Exercise"
        menu:
        - text: "Take Home Exercise 1"
          href: "Take-home_Ex01/Take-home_Ex01.qmd"

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

